# Generated by Django 2.2.7 on 2019-11-18 09:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gcontent',
            field=tinymce.models.HTMLField(),
        ),
    ]
